// Generated by CoffeeScript 1.4.0

jQuery(function() {
  $.each($("pre"), function(index, code) {
    return new CodeMirror(function(node) {
      if (code instanceof jQuery) {
        code = code.get(0);
      }
      console.log(code.textContent);
      return code.parentNode.replaceChild(node, code);
    }, {
      value: code.textContent.replace(/\n$/, ''),
      readOnly: true,
      mode: 'ruby',
      theme: "monokai",
      lineNumbers: $.trim(code.textContent).match("\\n"),
      matchBrackets: true
    });
  });
  return $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });
});
